# Generated by Django 3.1.6 on 2021-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosBtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('precioMax', models.FloatField()),
                ('precioMin', models.FloatField()),
            ],
        ),
    ]
